redis_loader: support loading GFFs via URL
legumeinfo/microservices pull request #38
Opened 2022-01-08 20:51 UTC by nathanweeks

`gffutils.create_db()` supports [loading a file via URL](http://daler.github.io/gffutils/changelog.html#changes-in-v0-8-3). It would be handy to allow the redis_loader to accept `--gene-gff`, `--chromosome-gff`, and `--gfa` option-arguments that are either file pathnames or URLs; this patch attempts to implement that by passing the arguments directly to gffutils.create_db() without first converting them to pathlib.Path objects (which collapses any '//' in URLs to '/').

The handling of urllib.requests.urlopen() encoding may not be the most elegant; it was taken from https://stackoverflow.com/a/18897408 .

2022-01-10 16:21 UTC, alancleary requested changes
This all looks good, in terms of content. However, the code follows the PEP 8 style guide; multiple lines of the PR violate PEP 8's [79 character line length limit](https://www.python.org/dev/peps/pep-0008/#maximum-line-length). Please update the code to conform before merging.

2022-01-11 01:53 UTC, nathanweeks commented
Will do. To verify that I'm not fixing one issue and creating another, is there a preferred command-line utility & set of options that can be used to validate changes? We could then automate linting in a GitHub Actions workflow.

2022-01-11 16:31 UTC, alancleary commented
> Will do. To verify that I'm not fixing one issue and creating another, is there a preferred command-line utility & set of options that can be used to validate changes? We could then automate linting in a GitHub Actions workflow.

Actually no. I just have a vertical bar drawn in vim at the 80 character mark.

Years ago when I was learning PEP 8 I would manually run a linter. But that was tedious so I stopped once I had internalized enough of it that I wasn't getting errors anymore (I was too much of a newb then to consider automation). So I'm sure if we ran a linter now my code would throw some errors and I would be crowned hypocrite extraordinaire!

That said, I am very open to the idea of automating linting and reformatting. I've been meaning to do it with the GCV client for years but am scared to because I haven't been following a TypeScript style guide at all and there's a lot of code!

So for this PR I think trimming down the lines that exceed 79 characters should suffice. But moving forward, selecting a linter and reformatter and then automating them would be a worthwhile endeavor. Starting with the microservices (instead of the GCV client) would be good because they're micro! i.e. small, manageable code.

2022-01-11 22:59 UTC, nathanweeks commented
OK, thanks! Just wanted to ensure I wasn't inadvertently initiating a game of whack-a-mole (I fixed the PEP8 79-character line length limitation, though pycodestyle points out indentation issues...). 

At some point, it probably would be helpful to formalize the desired PEP8 requirements that contributions are expected to conform to in a linter that's run via GitHub Actions workflow.

2022-01-11 23:04 UTC, alancleary approved these changes
Thanks for changing the line lengths. I'm looking forward to automating this!

2022-01-11 23:04 UTC, merged

2022-01-13 17:37 UTC, alancleary commented
@nathanweeks Let me know when you're done making changes to the Redis loader and I will tag a new release so they're included in the published image.

2022-01-14 12:47 UTC, nathanweeks commented
Done for now.

2022-01-27 10:58 UTC, nathanweeks commented
@alancleary Just a ping to see if you're planning to tag a new redis_loader version soon.

2022-01-27 18:37 UTC, alancleary commented
Sorry for the delay, Nathan! Is a redis_loader image with the changes of this PR all you need?

2022-01-27 23:00 UTC, nathanweeks commented
Actually, there's one more change to redis_loader that I would like to have reviewed before an update is released. Will push shortly.

2022-01-28 00:06 UTC, nathanweeks commented
OK, *shortly* might mean within the next couple days. I'd like to implement an equivalent of the `/docker-entrypoint-initdb.d` directory that the official Docker [mysql](https://hub.docker.com/_/mysql), [postgres](https://hub.docker.com/_/postgres), and [mongo](https://hub.docker.com/_/mongo) images use. Essentially, any loader shell scripts in that directory will be run as part of the ENTRYPOINT (if the redis db is empty). This should facilitate automated production deployment scenarios.

2022-01-28 16:12 UTC, alancleary commented
No worries. Just be sure to add instructions to the microservice's readme so I can test it before merging!

2022-01-28 23:43 UTC, nathanweeks commented
Done. The `docker-entrypoint-initdb.d/load.sh.sample` can be renamed to `load.sh` to test----though note I only tested by altering the "legumeinf/gcv" repo's `microservices/compose.yml` thus:
```
--- a/microservices/compose.yml
+++ b/microservices/compose.yml
@@ -216,10 +216,12 @@ services:
       - "traefik.http.routers.search.entrypoints=web"

   redis_loader:
-    image: ghcr.io/legumeinfo/microservices-redis_loader:1.0.0
+    image: redis_loader:test
     depends_on:
       redisearch:
         condition: service_healthy
     environment:
       REDIS_HOST: redisearch
+    volumes:
+      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
     profiles: [redis_loader]
```
where `microservices/docker-entrypoint-init.db/load.sh` is the load.sh.sample script, and invoking `docker compose up -d`, then `docker compose run --use-aliases redis_loader`.